export const successMessages = Object.freeze({
  REGISTER_SUCCESS: "Register successfully!",
  LOGIN_SUCCESS: "Login successfully!",
  CREATE_SUCCESS: "Create successfully!",
  DELETE_SUCCESS: "Delete successfully!",
  UPDATE_SUCCESS: "Update successfully!",
  GET_SUCCESS: "Get successfully!",
  LOGOUT_SUCCESS: "Logout successfully!",
  REFRESH_TOKEN_SUCCESS: "Refresh token successfully!",
  VERIFY_EMAIL_SUCCESS: "Verify email successfully!",
  FORGOT_PASSWORD_SUCCESS: "Forgot password successfully!",
  RESET_PASSWORD_SUCCESS: "Reset password successfully!",
  CHANGE_PASSWORD_SUCCESS: "Change password successfully!",
  UPDATE_PROFILE_SUCCESS: "Update profile successfully!",
  GET_PROFILE_SUCCESS: "Get profile successfully!",
  GET_LIST_SUCCESS: "Get list successfully!",
  GET_DETAIL_SUCCESS: "Get detail successfully!",
  CONNECT_DB_SUCCESS: "Connect database successfully!",
  RESET_PASSWORD_SUCCESS: "Reset password successfully!",
});

export const errorMessages = Object.freeze({
  TOKEN_INVALID: "Token invalid!",
  CONNECT_DB_FAIL: "Connect database fail!",
  NOT_FOUND: "NOT FOUND",
  CREATE_FAIL: "Create fail!",
  DELETE_FAIL: "Delete fail!",
  UPDATE_FAIL: "Update fail!",
  GET_FAIL: "Get fail!",
  LOGIN_FAIL: "Login fail!",
  REGISTER_FAIL: "Register fail!",
  UNAUTHORIZED: "Unauthorized!",
  SERVER_ERROR: "Server error!",
  EMAIL_EXIST: "Email already exists!",
  USERNAME_EXIST: "Username already exists!",
  EMAIL_NOT_FOUND: "Email not found!",
  PASSWORD_NOT_MATCH: "Password not match!",
  INVALID_EMAIL: "Invalid email!",
  INVALID_PASSWORD: "Invalid password!",
  PERMISSION_DENIED: "Permission denied!",
});
